### ISSUE TITLE
Roadmap for the Framework Implementation

### ISSUE THREAD

**Issue by dextermallo** [dextermallo/GSoC-2023#9]
> *This is a draft of the roadmap for the framework implementation and is under discussion.*

## Background

While the framework prototype is almost completed (interactive/pipeline mode), we should start considering the framework/utility roadmap. 

## Roadmap

The utility will have two primary modes:

### Interactive mode

Description: Interactive mode is for an individual (public user/CRS contributor) who wants to examine or evaluate the performance of the Core Rule Set — they intend to test on their own devices. In brief, the demands for the interactive mode are:
- Must-have
    - As a user, the utility must run on-prem.
    - As a user, the utility must collect matrices from rule changes.
    - As a user, the utility must yield outputs that can visually compare performance changes.
- Nice to have
    - As a user, the utility can be fully automated without too much manual work.
    - As a user, the utility has fine-grained information (e.g., multiple matrices from multiple data collectors)

Use cases: `WIP: Refer to the original doc`

### Pipeline (automated) mode

Description: Pipeline mode is primarily for the use of CI/CD. Ideally, we aim to integrate performance tests in the CI/CD pipeline In CoreRuleSet when a rule/test is changed. The demands are slightly different from the interactive mode:
- Must-have
    - As a CRS contributor, the utility must run on GitHub Action.
    - As a CRS contributor, the CI/CD action must be able to block/pass by evaluating the pre-configured thresholds.
    - As a CRS contributor, the threshold must be set on each rule.
- Nice to have
    - As a user, the utility can integrate into other CI/CD pipelines (e.g., GitLab Action)

Use cases: `WIP`

## To-dos (Wrapping up for GSoC submission)

- [x] Bug/Changes from previous comments.
- [x] Create reports for cAdvisor/locust.
- [x] Add threshold for cAdvisor/locust. (WIP)
- [x] Update test cases (prev code coverage: 91%)
- [x] Integrate into GitHub Action.
- [x] Update documentation.
- [x] Add a tutorial.
- [x] Project migration: move to CoreRuleSet

## Nice-to-have (plans in the future)
- [ ] Improve the user experience
    - [ ] Use custom CLI name (e.g. `crsp (crs performance) collect`) instead of `poetry run collect`
    - [ ] Fine-tune/add new args for commands, such as removing temporary files after running the commands.
    - [ ] Add visualization reports (image-based)
- [ ] Improvements in pipelines
    - [ ] For the command `report`, the text-based version works well on-prem, but it would be better with an HTML-based report for the GitHub Summary.
    - [ ] Threshold is designed for the pipeline. 
    - [ ] If feasible, it would be great if the summary could be shown as a comment in the PR.
- [ ] Enhance functionality/accuracy of existing utils: The implemented utils (`go-ftw`, `cAdvisor`, and `locust`) have several items that can be improved. For instance, locust runs N requests within 60 seconds, and M test cases share these requests. Specifically, some test cases might be run insufficiently.
- [ ] Add eBPF and other utils: adding more utils to enrich the matrices we can collect.
- [ ] Developer-related
    - [ ] Create markdown for contribution, security, etc.
